title: 咕咕文游APP
author: "blueloveTH"

theme: jekyll-theme-leap-day

# Minima: show excerpts in the homepage
show_excerpts: true

minima:
  date_format: "%Y-%m-%d"

# Minima: custom header links
header_pages: